import { randomUUID } from "node:crypto";

import { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import { buildApp } from "@/app.js";
import { PgAuthRepository } from "@/modules/auth/repositories/auth.repository.js";
import { PERMISSIONS } from "@/modules/permissions/permission-catalog.js";
import { PgPermissionRepository } from "@/modules/permissions/repositories/permission.repository.js";
import { RoleRepository } from "@/modules/roles/repositories/role.repository.js";
import { hashPassword } from "@/modules/users/services/password-hasher.js";

const url = process.env.TEST_DATABASE_URL;
const schema = `it_access_${randomUUID().replaceAll("-", "")}`;
const secret = "test-secret-scrum-432-postgres-only";
describe.skipIf(!url)("permissions and authentication (Postgres real)", () => {
  let pool: Pool;
  let repository: PgPermissionRepository;
  let roles: RoleRepository;
  let hash: string;
  beforeAll(async () => {
    hash = await hashPassword("password123");
    const admin = new Pool({ connectionString: url });
    try {
      await admin.query(`CREATE SCHEMA ${schema};
        CREATE TABLE ${schema}.roles (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(50) NOT NULL UNIQUE, description varchar(255), created_at timestamp NOT NULL DEFAULT current_timestamp);
        CREATE TABLE ${schema}.permissions (code varchar(100) PRIMARY KEY, description varchar(255) NOT NULL);
        CREATE TABLE ${schema}.role_permissions (role_id integer REFERENCES ${schema}.roles(id) ON DELETE CASCADE, permission_code varchar(100) REFERENCES ${schema}.permissions(code) ON DELETE RESTRICT, PRIMARY KEY(role_id, permission_code));
        CREATE TABLE ${schema}.users (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id integer NOT NULL REFERENCES ${schema}.roles(id) ON DELETE RESTRICT, name varchar(150) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamp NOT NULL DEFAULT current_timestamp);
        CREATE TABLE ${schema}.credentials (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL UNIQUE REFERENCES ${schema}.users(id) ON DELETE CASCADE, email varchar(150) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL);
      `);
    } finally {
      await admin.end();
    }
    pool = new Pool({
      connectionString: url,
      options: `-c search_path=${schema}`,
    });
    repository = new PgPermissionRepository(pool);
    roles = new RoleRepository(pool);
    await pool.query(
      "INSERT INTO permissions SELECT * FROM unnest($1::text[], $2::text[])",
      [
        PERMISSIONS.map((permission) => permission.code),
        PERMISSIONS.map((permission) => permission.description),
      ],
    );
  });
  beforeEach(async () => {
    await pool.query(
      "TRUNCATE credentials, users, role_permissions, roles RESTART IDENTITY",
    );
    await roles.create({ name: "Administrador", description: null });
    await roles.create({ name: "Client", description: null });
    await repository.replace(
      1,
      PERMISSIONS.map((permission) => permission.code),
    );
    await pool.query(
      "INSERT INTO users (role_id, name) VALUES (1, 'Admin'), (2, 'Client')",
    );
    await pool.query(
      "INSERT INTO credentials (user_id, email, password_hash) VALUES (1, 'admin@example.com', $1), (2, 'client@example.com', $1)",
      [hash],
    );
  });
  afterAll(async () => {
    const admin = new Pool({ connectionString: url });
    try {
      await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
    } finally {
      await admin.end();
      await pool?.end();
    }
  });

  it("persists sorted grants, clears them and rejects missing roles", async () => {
    expect(await repository.list()).toEqual(PERMISSIONS);
    expect(await repository.findByRoleId(2)).toEqual([]);
    expect(
      await repository.replace(2, ["users.read", "stations.read"]),
    ).toEqual(["stations.read", "users.read"]);
    expect(await repository.findByRoleIds([1, 2])).toMatchObject(
      new Map([
        [1, PERMISSIONS.map((permission) => permission.code)],
        [2, ["stations.read", "users.read"]],
      ]),
    );
    expect(await repository.replace(2, [])).toEqual([]);
    expect(await repository.findByRoleId(999)).toBeNull();
    await expect(repository.replace(999, [])).rejects.toMatchObject({
      statusCode: 404,
    });
  });

  it("rolls back unknown and duplicate grants without losing the old set", async () => {
    await repository.replace(2, ["monitoring.read"]);
    for (const permissions of [["unknown"], ["users.read", "users.read"]]) {
      await expect(repository.replace(2, permissions)).rejects.toMatchObject({
        statusCode: 400,
      });
      expect(await repository.findByRoleId(2)).toEqual(["monitoring.read"]);
    }
  });

  it("serializes concurrent replacements instead of merging their sets", async () => {
    const first = ["users.read", "stations.read"].sort();
    const second = ["monitoring.read", "properties.read"].sort();
    await Promise.all([
      repository.replace(2, first),
      repository.replace(2, second),
    ]);
    expect([first, second]).toContainEqual(await repository.findByRoleId(2));
  });

  it("preserves profile grants on edits and cascades them only after references are removed", async () => {
    await repository.replace(2, ["monitoring.read"]);
    await roles.update(2, { name: "Renamed", description: null });
    expect(await repository.findByRoleId(2)).toEqual(["monitoring.read"]);
    await expect(roles.delete(2)).rejects.toMatchObject({ statusCode: 409 });
    await pool.query("DELETE FROM users WHERE role_id = 2");
    expect(await roles.delete(2)).toBe(true);
    expect(await repository.findByRoleIds([2])).toEqual(new Map());
  });

  it("reads credential hashes only for login and current permissions for authentication", async () => {
    const auth = new PgAuthRepository(pool);
    expect(await auth.findCredentialByEmail("admin@example.com")).toMatchObject(
      {
        id: 1,
        password_hash: hash,
        permissions: PERMISSIONS.map((permission) => permission.code),
      },
    );
    expect(await auth.findUserById(1)).not.toHaveProperty("password_hash");
    await repository.replace(2, ["users.read"]);
    expect(await auth.findUserById(2)).toMatchObject({
      permissions: ["users.read"],
    });
  });
});
