import { randomUUID } from "node:crypto";

import { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import {
  RoleDeletionConflictError,
  RoleNameConflictError,
} from "@/modules/roles/errors/role.errors.js";
import { RoleRepository } from "@/modules/roles/repositories/role.repository.js";

const TEST_DATABASE_URL = process.env.TEST_DATABASE_URL;
const schema = `it_roles_${randomUUID().replaceAll("-", "")}`;

describe.skipIf(!TEST_DATABASE_URL)("RoleRepository (Postgres real)", () => {
  let pool: Pool;
  let repository: RoleRepository;

  beforeAll(async () => {
    const admin = new Pool({ connectionString: TEST_DATABASE_URL });
    try {
      await admin.query(`CREATE SCHEMA ${schema}`);
      await admin.query(`
        CREATE TABLE ${schema}.roles (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name varchar(50) NOT NULL UNIQUE,
          description varchar(255),
          created_at timestamp NOT NULL DEFAULT current_timestamp
        );
        CREATE TABLE ${schema}.users (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          role_id integer NOT NULL REFERENCES ${schema}.roles (id) ON DELETE RESTRICT,
          name varchar(150) NOT NULL,
          active boolean NOT NULL DEFAULT true,
          created_at timestamp NOT NULL DEFAULT current_timestamp
        );
        CREATE TABLE ${schema}.credentials (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id integer NOT NULL UNIQUE REFERENCES ${schema}.users (id) ON DELETE CASCADE,
          email varchar(150) NOT NULL UNIQUE,
          password_hash varchar(255) NOT NULL
        );
      `);
    } finally {
      await admin.end();
    }
    pool = new Pool({
      connectionString: TEST_DATABASE_URL,
      options: `-c search_path=${schema}`,
    });
    repository = new RoleRepository(pool);
  });

  beforeEach(async () => {
    await pool.query("TRUNCATE credentials, users, roles RESTART IDENTITY");
  });

  afterAll(async () => {
    const admin = new Pool({ connectionString: TEST_DATABASE_URL });
    try {
      await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
    } finally {
      await admin.end();
      await pool?.end();
    }
  });

  it("persists CRUD, ordering, timestamps and missing records", async () => {
    expect(await repository.findAll()).toEqual([]);
    const first = await repository.create({
      name: "Manager",
      description: "Reports",
    });
    const second = await repository.create({
      name: "Analyst",
      description: null,
    });
    expect(await repository.findAll()).toEqual([first, second]);
    expect(await repository.findById(first.id)).toEqual(first);
    expect(first.created_at).toMatch(/^\d{4}-\d{2}-\d{2}T.*Z$/);
    expect(
      await repository.update(first.id, {
        name: "Supervisor",
        description: null,
      }),
    ).toEqual({ ...first, name: "Supervisor", description: null });
    expect(await repository.exists(first.id)).toBe(true);
    expect(await repository.delete(first.id)).toBe(true);
    expect(await repository.exists(first.id)).toBe(false);
    expect(await repository.findById(first.id)).toBeNull();
    expect(
      await repository.update(first.id, { name: "Missing", description: null }),
    ).toBeNull();
    expect(await repository.delete(first.id)).toBe(false);
  });

  it("enforces exact name uniqueness on create and update", async () => {
    const first = await repository.create({
      name: "Manager",
      description: null,
    });
    const second = await repository.create({
      name: "Analyst",
      description: null,
    });
    await expect(
      repository.create({ name: "Manager", description: null }),
    ).rejects.toBeInstanceOf(RoleNameConflictError);
    await expect(
      repository.update(second.id, { name: "Manager", description: null }),
    ).rejects.toBeInstanceOf(RoleNameConflictError);
    expect(await repository.findById(second.id)).toEqual(second);
    await expect(
      repository.update(first.id, { name: "Manager", description: "Changed" }),
    ).resolves.toMatchObject({ id: first.id, description: "Changed" });
    await expect(
      repository.create({ name: "manager", description: null }),
    ).resolves.toMatchObject({ name: "manager" });
  });

  it("allows only one concurrent creation with the same name", async () => {
    const results = await Promise.allSettled([
      repository.create({ name: "Manager", description: null }),
      repository.create({ name: "Manager", description: null }),
    ]);
    expect(
      results.filter((result) => result.status === "fulfilled"),
    ).toHaveLength(1);
    const rejected = results.find((result) => result.status === "rejected");
    expect(rejected?.reason).toBeInstanceOf(RoleNameConflictError);
    expect(await repository.findAll()).toHaveLength(1);
  });

  it.each([true, false])(
    "blocks deletion with an associated user (active=%s)",
    async (active) => {
      const role = await repository.create({
        name: "Manager",
        description: null,
      });
      await pool.query(
        "INSERT INTO users (role_id, name, active) VALUES ($1, $2, $3)",
        [role.id, "Test user", active],
      );
      await expect(repository.delete(role.id)).rejects.toBeInstanceOf(
        RoleDeletionConflictError,
      );
      expect(await repository.findById(role.id)).toEqual(role);
      await pool.query("DELETE FROM users WHERE role_id = $1", [role.id]);
      expect(await repository.delete(role.id)).toBe(true);
    },
  );
});
