import { Pool } from "pg";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

import {
  PgAlertConfigRepository,
  PgTriggeredAlertRepository,
} from "@/modules/alerts/repositories/pg-alert.repository.js";

// Testes de integração dos repositórios Postgres. Rodam só quando
// TEST_DATABASE_URL aponta para um Postgres descartável (o CI sobe um).
// Tudo acontece num schema próprio, apagado no fim: nunca toca tabelas reais.
const TEST_DATABASE_URL = process.env.TEST_DATABASE_URL;
const SCHEMA = `it_alerts_${process.pid}`;

describe.skipIf(!TEST_DATABASE_URL)(
  "Pg alert repositories (Postgres real)",
  () => {
    let pool: Pool;
    let configs: PgAlertConfigRepository;
    let triggered: PgTriggeredAlertRepository;

    const config = (sensorId = 1) => ({
      manager_user_id: null,
      sensor_id: sensorId,
      reference_value: 35.5,
      comparison_operator: ">" as const,
      message: null,
      active: true,
    });

    beforeAll(async () => {
      const admin = new Pool({ connectionString: TEST_DATABASE_URL });
      await admin.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
      await admin.query(`CREATE SCHEMA ${SCHEMA}`);
      await admin.query(`
      CREATE TABLE ${SCHEMA}.sensors (id integer PRIMARY KEY);
      INSERT INTO ${SCHEMA}.sensors (id) VALUES (1), (2);
      CREATE TABLE ${SCHEMA}.readings (
        id bigint PRIMARY KEY, value decimal(10,2), unix_time bigint
      );
      INSERT INTO ${SCHEMA}.readings VALUES (500, 31.25, 1790000000);
      CREATE TABLE ${SCHEMA}.alert_configs (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        manager_user_id integer NULL,
        sensor_id integer NOT NULL REFERENCES ${SCHEMA}.sensors (id),
        reference_value decimal(8,2) NOT NULL,
        comparison_operator varchar(2) NOT NULL,
        message varchar(200) NULL,
        active boolean NOT NULL DEFAULT true,
        created_at timestamp NOT NULL DEFAULT current_timestamp
      );
      CREATE TABLE ${SCHEMA}.triggered_alerts (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        alert_config_id integer NOT NULL
          REFERENCES ${SCHEMA}.alert_configs (id) ON DELETE CASCADE,
        reading_id bigint NOT NULL,
        acknowledged_by integer NULL,
        triggered_at timestamp NOT NULL DEFAULT current_timestamp,
        acknowledged_at timestamp NULL
      );
      CREATE UNIQUE INDEX ON ${SCHEMA}.triggered_alerts (reading_id, alert_config_id);
      CREATE UNIQUE INDEX ON ${SCHEMA}.triggered_alerts (alert_config_id)
        WHERE acknowledged_at IS NULL;
    `);
      await admin.end();

      pool = new Pool({
        connectionString: TEST_DATABASE_URL,
        options: `-c search_path=${SCHEMA}`,
      });
      configs = new PgAlertConfigRepository(pool);
      triggered = new PgTriggeredAlertRepository(pool);
    });

    beforeEach(async () => {
      await pool.query(
        "TRUNCATE triggered_alerts, alert_configs RESTART IDENTITY CASCADE",
      );
    });

    afterAll(async () => {
      await pool?.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
      await pool?.end();
    });

    it("should_keep_the_real_config_total_when_page_is_beyond_the_last", async () => {
      for (let n = 0; n < 3; n += 1) await configs.create(config());

      const result = await configs.findMany({ page: 9, limit: 2 });

      expect(result).toEqual({ data: [], total_records: 3 });
    });

    it("should_paginate_configs_with_filter_and_numeric_types", async () => {
      await configs.create(config(1));
      await configs.create(config(2));
      await configs.create(config(1));

      const result = await configs.findMany({
        page: 2,
        limit: 1,
        sensor_id: 1,
      });

      expect(result.total_records).toBe(2);
      expect(result.data.map((c) => c.id)).toEqual([3]);
      expect(result.data[0]!.reference_value).toBe(35.5);
    });

    it("should_keep_the_real_triggered_total_when_page_is_beyond_the_last", async () => {
      for (let n = 1; n <= 3; n += 1) {
        const { id } = await configs.create(config());
        await triggered.create({ alert_config_id: id, reading_id: n });
      }

      const result = await triggered.findMany({ page: 4, limit: 1 });

      expect(result).toEqual({ data: [], total_records: 3 });
    });

    it("should_return_the_reading_value_that_triggered_the_alert", async () => {
      const created = await configs.create(config(1));
      const withReading = (await triggered.create({
        alert_config_id: created.id,
        reading_id: 500,
      }))!;
      await triggered.acknowledge(Number(withReading.id), 7);
      const withoutReading = await triggered.create({
        alert_config_id: created.id,
        reading_id: 999,
      });

      expect(withReading).toMatchObject({
        reading_value: 31.25,
        reading_unix_time: 1790000000,
      });
      expect(withoutReading).toMatchObject({
        reading_value: null,
        reading_unix_time: null,
      });
      const listed = await triggered.findMany({ page: 1, limit: 10 });
      expect(listed.data.map((a) => a.reading_value)).toEqual([null, 31.25]);
    });

    it("should_acknowledge_only_once_even_when_concurrent", async () => {
      const { id: configId } = await configs.create(config());
      const alert = (await triggered.create({
        alert_config_id: configId,
        reading_id: 1,
      }))!;

      const results = await Promise.all([
        triggered.acknowledge(Number(alert.id), 7),
        triggered.acknowledge(Number(alert.id), 8),
      ]);

      const winners = results.filter((r) => r !== null);
      expect(winners).toHaveLength(1);
      const stored = await triggered.findById(Number(alert.id));
      expect(stored?.acknowledged_by).toBe(winners[0]!.acknowledged_by);
    });

    it("should_return_null_when_acknowledging_an_already_acknowledged_alert", async () => {
      const { id: configId } = await configs.create(config());
      const alert = (await triggered.create({
        alert_config_id: configId,
        reading_id: 1,
      }))!;
      await triggered.acknowledge(Number(alert.id), 7);

      await expect(
        triggered.acknowledge(Number(alert.id), 8),
      ).resolves.toBeNull();
      expect(
        (await triggered.findById(Number(alert.id)))?.acknowledged_by,
      ).toBe(7);
    });

    it("should_keep_a_single_pending_alert_per_config_even_when_concurrent", async () => {
      const { id } = await configs.create(config());

      const results = await Promise.all([
        triggered.create({ alert_config_id: id, reading_id: 1 }),
        triggered.create({ alert_config_id: id, reading_id: 2 }),
      ]);

      expect(results.filter((r) => r !== null)).toHaveLength(1);
      const listed = await triggered.findMany({
        page: 1,
        limit: 10,
        acknowledged: false,
      });
      expect(listed.total_records).toBe(1);
    });

    it("should_allow_a_new_pending_alert_after_the_previous_is_acknowledged", async () => {
      const { id } = await configs.create(config());
      const first = (await triggered.create({
        alert_config_id: id,
        reading_id: 1,
      }))!;
      await expect(
        triggered.create({ alert_config_id: id, reading_id: 2 }),
      ).resolves.toBeNull();

      await triggered.acknowledge(Number(first.id), 7);

      await expect(
        triggered.create({ alert_config_id: id, reading_id: 3 }),
      ).resolves.toMatchObject({ alert_config_id: id, acknowledged_at: null });
    });

    it("should_report_pending_alerts_per_config", async () => {
      const { id: withPending } = await configs.create(config());
      const { id: allAcknowledged } = await configs.create(config());
      await triggered.create({ alert_config_id: withPending, reading_id: 1 });
      const done = (await triggered.create({
        alert_config_id: allAcknowledged,
        reading_id: 2,
      }))!;
      await triggered.acknowledge(Number(done.id), 7);

      await expect(triggered.hasPendingForConfig(withPending)).resolves.toBe(
        true,
      );
      await expect(
        triggered.hasPendingForConfig(allAcknowledged),
      ).resolves.toBe(false);
    });
  },
);
