import { randomUUID } from "node:crypto";

import { Pool } from "pg";
import {
  afterAll,
  beforeAll,
  beforeEach,
  describe,
  expect,
  it,
  vi,
} from "vitest";

import { buildApp } from "@/app.js";
import { PgAuthRepository } from "@/modules/auth/repositories/auth.repository.js";
import { LoginService } from "@/modules/auth/services/login.service.js";
import { InMemoryMonitoringRepository } from "@/modules/monitoring/repositories/monitoring.repository.js";
import { ReadingsBroadcaster } from "@/modules/monitoring/services/readings-broadcaster.js";
import { PERMISSIONS } from "@/modules/permissions/permission-catalog.js";
import { UserRepository } from "@/modules/users/repositories/user.repository.js";
import { hashPassword } from "@/modules/users/services/password-hasher.js";
import { UpdateUserAccessService } from "@/modules/users/services/update-user-access.service.js";

const url = process.env.TEST_DATABASE_URL;
const schema = `it_user_access_${randomUUID().replaceAll("-", "")}`;

describe.skipIf(!url)("user access (Postgres real)", () => {
  let pool: Pool;
  let repository: UserRepository;
  let hash: string;

  beforeAll(async () => {
    hash = await hashPassword("password123");
    const admin = new Pool({ connectionString: url });
    try {
      await admin.query(`CREATE SCHEMA ${schema};
        CREATE TABLE ${schema}.roles (id integer PRIMARY KEY, name varchar(50) NOT NULL);
        CREATE TABLE ${schema}.users (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, role_id integer NOT NULL REFERENCES ${schema}.roles(id) ON DELETE RESTRICT, name varchar(150) NOT NULL, active boolean NOT NULL DEFAULT true, created_at timestamp NOT NULL DEFAULT current_timestamp);
        CREATE TABLE ${schema}.credentials (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id integer NOT NULL UNIQUE REFERENCES ${schema}.users(id) ON DELETE CASCADE, email varchar(150) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL);
        CREATE TABLE ${schema}.permissions (code varchar(100) PRIMARY KEY, description varchar(255) NOT NULL);
        CREATE TABLE ${schema}.role_permissions (role_id integer REFERENCES ${schema}.roles(id) ON DELETE CASCADE, permission_code varchar(100) REFERENCES ${schema}.permissions(code), PRIMARY KEY(role_id, permission_code));
      `);
    } finally {
      await admin.end();
    }
    pool = new Pool({
      connectionString: url,
      options: `-c search_path=${schema}`,
    });
    repository = new UserRepository(pool);
    await pool.query(
      "INSERT INTO roles VALUES (1, 'Administrator'), (2, 'Viewer')",
    );
    await pool.query(
      "INSERT INTO permissions SELECT * FROM unnest($1::text[], $2::text[])",
      [
        PERMISSIONS.map((permission) => permission.code),
        PERMISSIONS.map((permission) => permission.description),
      ],
    );
    await pool.query(
      "INSERT INTO role_permissions SELECT 1, code FROM permissions",
    );
    await pool.query(
      "INSERT INTO role_permissions VALUES (2, 'monitoring.read')",
    );
  });

  beforeEach(async () => {
    await pool.query("TRUNCATE credentials, users RESTART IDENTITY");
    await repository.create({
      roleId: 1,
      name: "Operator",
      email: "operator@example.com",
      passwordHash: hash,
      active: true,
    });
    await repository.create({
      roleId: 2,
      name: "Viewer",
      email: "viewer@example.com",
      passwordHash: hash,
      active: true,
    });
  });

  afterAll(async () => {
    const admin = new Pool({ connectionString: url });
    try {
      await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`);
    } finally {
      await admin.end();
      await pool?.end();
    }
  });

  it("persists block and unblock while preserving identity, credentials and grants", async () => {
    const initial = (await repository.findById(2))!;
    const service = new UpdateUserAccessService(repository);
    expect(await service.update(2, { active: false })).toEqual({
      ...initial,
      active: false,
    });
    expect(await new UserRepository(pool).findById(2)).toEqual({
      ...initial,
      active: false,
    });
    expect(await service.update(2, { active: false })).toEqual({
      ...initial,
      active: false,
    });
    expect(await service.update(2, { active: true })).toEqual(initial);
    expect(await service.update(2, { active: true })).toEqual(initial);
    expect(
      (
        await pool.query(
          "SELECT password_hash FROM credentials WHERE user_id = 2",
        )
      ).rows[0].password_hash,
    ).toBe(hash);
    expect(
      (await new PgAuthRepository(pool).findUserById(2))!.permissions,
    ).toEqual(["monitoring.read"]);
  });

  it("returns missing for absent or credential-less users without changing their state", async () => {
    expect(await repository.updateAccess(999, false)).toBeNull();
    const orphan = await pool.query(
      "INSERT INTO users (role_id, name) VALUES (2, 'No credential') RETURNING id",
    );
    const id = orphan.rows[0].id as number;
    expect(await repository.updateAccess(id, false)).toBeNull();
    expect(
      (await pool.query("SELECT active FROM users WHERE id = $1", [id])).rows[0]
        .active,
    ).toBe(true);
  });

  it("does not overwrite a concurrent profile edit", async () => {
    await Promise.all([
      pool.query("UPDATE users SET name = $2, role_id = $3 WHERE id = $1", [
        2,
        "Renamed",
        1,
      ]),
      repository.updateAccess(2, false),
    ]);
    expect(await repository.findById(2)).toMatchObject({
      id: 2,
      name: "Renamed",
      role_id: 1,
      active: false,
      email: "viewer@example.com",
    });
  });

  it("denies login while blocked and restores it after unblocking", async () => {
    const login = new LoginService(new PgAuthRepository(pool));
    expect(
      await login.login("viewer@example.com", "password123"),
    ).toMatchObject({ id: 2, active: true });
    await repository.updateAccess(2, false);
    await expect(
      login.login("viewer@example.com", "password123"),
    ).rejects.toMatchObject({ statusCode: 401 });
    await repository.updateAccess(2, true);
    expect(
      await login.login("viewer@example.com", "password123"),
    ).toMatchObject({ id: 2, active: true });
  });
  it.each([false, true])(
    "blocks and restores access through the protected API (legacy protection=%s)",
    async (enabled) => {
      const app = buildApp({
        database: pool,
        jwtSecret: "test-secret-scrum-433-postgres-only",
        accessControlEnabled: enabled,
        monitoringRepository: new InMemoryMonitoringRepository(),
      });
      try {
        const initial = await repository.findById(2);
        const operatorLogin = await app.inject({
          method: "POST",
          url: "/api/auth/login",
          payload: { email: "operator@example.com", password: "password123" },
        });
        const viewerLogin = await app.inject({
          method: "POST",
          url: "/api/auth/login",
          payload: { email: "viewer@example.com", password: "password123" },
        });
        expect(operatorLogin.statusCode).toBe(200);
        expect(viewerLogin.statusCode).toBe(200);
        const operatorHeaders = {
          authorization: `Bearer ${operatorLogin.json().access_token}`,
        };
        const viewerHeaders = {
          authorization: `Bearer ${viewerLogin.json().access_token}`,
        };
        expect(
          (await app.inject({ url: "/api/auth/me", headers: viewerHeaders }))
            .statusCode,
        ).toBe(200);
        expect(
          (
            await app.inject({
              url: "/api/stations/current",
              headers: viewerHeaders,
            })
          ).statusCode,
        ).toBe(200);
        const patch = (active: boolean) =>
          app.inject({
            method: "PATCH",
            url: "/api/users/2/access",
            headers: operatorHeaders,
            payload: { active },
          });
        expect(
          (
            await app.inject({
              method: "PATCH",
              url: "/api/users/2/access",
              headers: viewerHeaders,
              payload: { active: false },
            })
          ).statusCode,
        ).toBe(403);
        const blocked = await patch(false);
        expect(blocked.statusCode).toBe(200);
        expect(blocked.json()).toEqual({ ...initial, active: false });
        expect((await patch(false)).statusCode).toBe(200);
        expect(
          (
            await app.inject({ url: "/api/users/2", headers: operatorHeaders })
          ).json(),
        ).toEqual({ ...initial, active: false });
        expect((await repository.findById(2))!.active).toBe(false);
        expect(
          (
            await app.inject({
              method: "POST",
              url: "/api/auth/login",
              payload: { email: "viewer@example.com", password: "password123" },
            })
          ).statusCode,
        ).toBe(401);
        for (const path of [
          "/api/auth/me",
          "/api/permissions",
          "/api/roles/2/permissions",
        ]) {
          expect(
            (await app.inject({ url: path, headers: viewerHeaders }))
              .statusCode,
          ).toBe(401);
        }
        if (enabled)
          expect(
            (
              await app.inject({
                url: "/api/stations/current",
                headers: viewerHeaders,
              })
            ).statusCode,
          ).toBe(401);
        expect(
          (
            await app.inject({
              method: "PATCH",
              url: "/api/users/2/access",
              headers: viewerHeaders,
              payload: { active: true },
            })
          ).statusCode,
        ).toBe(401);
        const unblocked = await patch(true);
        expect(unblocked.statusCode).toBe(200);
        expect(unblocked.json()).toEqual(initial);
        expect((await patch(true)).statusCode).toBe(200);
        expect(
          (await app.inject({ url: "/api/auth/me", headers: viewerHeaders }))
            .statusCode,
        ).toBe(200);
        expect(
          (
            await app.inject({
              url: "/api/stations/current",
              headers: viewerHeaders,
            })
          ).statusCode,
        ).toBe(200);
        expect(
          (
            await app.inject({
              method: "POST",
              url: "/api/auth/login",
              payload: { email: "viewer@example.com", password: "password123" },
            })
          ).statusCode,
        ).toBe(200);
        expect(
          (
            await pool.query(
              "SELECT password_hash FROM credentials WHERE user_id = 2",
            )
          ).rows[0].password_hash,
        ).toBe(hash);
      } finally {
        await app.close();
      }
    },
  );

  it("closes an existing WebSocket when blocked and allows reconnection after unblock", async () => {
    const monitoring = new InMemoryMonitoringRepository();
    const broadcaster = new ReadingsBroadcaster(monitoring, { intervalMs: 20 });
    const baseline = vi.spyOn(monitoring, "lastReadingId");
    const app = buildApp({
      database: pool,
      jwtSecret: "test-secret-scrum-433-websocket-only",
      accessControlEnabled: true,
      monitoringRepository: monitoring,
      readingsBroadcaster: broadcaster,
    });
    const reading = (id: number) => ({
      reading_id: id,
      station_id: 1,
      sensor_id: 1,
      local_identifier: "temp",
      sensor_type_id: 1,
      sensor_type: "Temperatura",
      unit_of_measure: "C",
      value: 20 + id,
      unix_time: 1790000000 + id,
    });
    try {
      await app.ready();
      const operatorHeaders = {
        authorization: `Bearer ${app.jwt.sign({ sub: "1" })}`,
      };
      const viewerHeaders = {
        authorization: `Bearer ${app.jwt.sign({ sub: "2" })}`,
      };
      const socket = await app.injectWS("/api/stations/current/ws", {
        headers: viewerHeaders,
      });
      const messages: unknown[] = [];
      socket.on("message", (data) => messages.push(JSON.parse(String(data))));
      const closed = new Promise<number>((resolve) =>
        socket.on("close", (code) => resolve(code)),
      );
      await vi.waitFor(() => expect(baseline).toHaveResolved(), {
        timeout: 3000,
      });
      monitoring.liveReadings.push(reading(1));
      await vi.waitFor(() => expect(messages).toHaveLength(1), {
        timeout: 3000,
      });
      expect(
        (
          await app.inject({
            method: "PATCH",
            url: "/api/users/2/access",
            headers: operatorHeaders,
            payload: { active: false },
          })
        ).statusCode,
      ).toBe(200);
      expect(await closed).toBe(1008);
      await vi.waitFor(() => {
        expect(broadcaster.subscribers).toBe(0);
        expect(broadcaster.isPolling).toBe(false);
      });
      monitoring.liveReadings.push(reading(2));
      expect(messages).toEqual([{ type: "reading", ...reading(1) }]);
      await expect(
        app.injectWS("/api/stations/current/ws", { headers: viewerHeaders }),
      ).rejects.toThrow("401");
      expect(
        (
          await app.inject({
            method: "PATCH",
            url: "/api/users/2/access",
            headers: operatorHeaders,
            payload: { active: true },
          })
        ).statusCode,
      ).toBe(200);
      baseline.mockClear();
      const restored = await app.injectWS("/api/stations/current/ws", {
        headers: viewerHeaders,
      });
      const restoredMessages: unknown[] = [];
      restored.on("message", (data) =>
        restoredMessages.push(JSON.parse(String(data))),
      );
      await vi.waitFor(() => expect(baseline).toHaveResolved(), {
        timeout: 3000,
      });
      monitoring.liveReadings.push(reading(3));
      await vi.waitFor(
        () =>
          expect(restoredMessages).toEqual([
            { type: "reading", ...reading(3) },
          ]),
        { timeout: 3000 },
      );
      restored.terminate();
    } finally {
      await app.close();
    }
  }, 15000);
});
